export const libros = [
  {
    name: "Génesis",
    chapter: "spa-RVR1960:Gen",
    posicion: 1,
  },
  {
    name: "Exodo",
    chapter: "spa-RVR1960:Exod",
    posicion: 41,
  },
  {
    name: "Levítoco",
    chapter: "spa-RVR1960:Lev",
    posicion: 20,
  },
  {
    name: "Números",
    chapter: "spa-RVR1960:Num",
    posicion: 51,
  },
  {
    name: "Deuteronomio",
    chapter: "spa-RVR1960:Deut",
    posicion: 16,
  },
  {
    name: "Josué",
    chapter: "spa-RVR1960:Josh",
    posicion: 7,
  },
  {
    name: "Jueces",
    chapter: "spa-RVR1960:Judg",
    posicion: 22,
  },
  {
    name: "Rut",
    chapter: "spa-RVR1960:Ruth",
    posicion: 0,
  },
  {
    name: "Samuel 1",
    chapter: "spa-RVR1960:1Sam",
    posicion: 2,
  },
  {
    name: "Samuel 2",
    chapter: "spa-RVR1960:2Sam",
    posicion: 50,
  },
  {
    name: "Reyes 1",
    chapter: "spa-RVR1960:1Kgs",
    posicion: 40,
  },
  {
    name: "Reyes 2",
    chapter: "spa-RVR1960:2Kgs",
    posicion: 33,
  },
  {
    name: "Crónicas 1",
    chapter: "spa-RVR1960:1Chr",
    posicion: 37,
  },
  {
    name: "Crónicas 2",
    chapter: "spa-RVR1960:2Chr",
    posicion: 15,
  },
  {
    name: "Esdras",
    chapter: "spa-RVR1960:Ezra",
    posicion: 9,
  },
  {
    name: "Nehemías",
    chapter: "spa-RVR1960:Neh",
    posicion: 52,
  },
  {
    name: "Ester",
    chapter: "spa-RVR1960:Esth",
    posicion: 3,
  },
  {
    name: "Job",
    chapter: "spa-RVR1960:Job",
    posicion: 17,
  },
  {
    name: "Salmos",
    chapter: "spa-RVR1960:Ps",
    posicion: 53,
  },
  {
    name: "Proverbios",
    chapter: "spa-RVR1960:Prov",
    posicion: 10,
  },
  {
    name: "Eclesiastés",
    chapter: "spa-RVR1960:Eccl",
    posicion: 4,
  },
  {
    name: "Cantares",
    chapter: "spa-RVR1960:Song",
    posicion: 34,
  },
  {
    name: "Isaías",
    chapter: "spa-RVR1960:Isa",
    posicion: 61,
  },
  {
    name: "Jeremías",
    chapter: "spa-RVR1960:Jer",
    posicion: 27,
  },
  {
    name: "Lamentaciones",
    chapter: "spa-RVR1960:Lam",
    posicion: 8,
  },
  {
    name: "Ezequiel",
    chapter: "spa-RVR1960:Ezek",
    posicion: 23,
  },
  {
    name: "Daniel",
    chapter: "spa-RVR1960:Dan",
    posicion: 28,
  },
  {
    name: "Oseas",
    chapter: "spa-RVR1960:Hos",
    posicion: 11,
  },
  {
    name: "Joel",
    chapter: "spa-RVR1960:Joel",
    posicion: 62,
  },
  {
    name: "Amós",
    chapter: "spa-RVR1960:Amos",
    posicion: 24,
  },
  {
    name: "Abdías",
    chapter: "spa-RVR1960:Obad",
    posicion: 54,
  },
  {
    name: "Jonás",
    chapter: "spa-RVR1960:Jonah",
    posicion: 21,
  },
  {
    name: "Miqueas",
    chapter: "spa-RVR1960:Mic",
    posicion: 29,
  },
  {
    name: "Nahum",
    chapter: "spa-RVR1960:Nah",
    posicion: 30,
  },
  {
    name: "Habacuc",
    posicion: 31,
    chapter: "spa-RVR1960:Hab",
  },
  {
    name: "Sofonías",
    chapter: "spa-RVR1960:Zeph",
    posicion: 18,
  },
  {
    name: "Hageo",
    chapter: "spa-RVR1960:Hag",
    posicion: 25,
  },
  {
    name: "Zacarías",
    chapter: "spa-RVR1960:Zech",
    posicion: 12,
  },
  {
    name: "Malaquías",
    chapter: "spa-RVR1960:Mal",
    posicion: 44,
  },
  {
    name: "Mateo",
    chapter: "spa-RVR1960:Matt",
    posicion: 38,
  },
  {
    name: "Marcos",
    chapter: "spa-RVR1960:Mark",
    posicion: 45,
  },
  {
    name: "Lucas",
    chapter: "spa-RVR1960:Luke",
    posicion: 43,
  },
  {
    name: "Juan",
    chapter: "spa-RVR1960:John",
    posicion: 55,
  },
  {
    name: "Hechos",
    chapter: "spa-RVR1960:Acts",
    posicion: 42,
  },
  {
    name: "Romanos",
    chapter: "spa-RVR1960:Rom",
    posicion: 32,
  },
  {
    name: "Corintios 1",
    chapter: "spa-RVR1960:1Cor",
    posicion: 39,
  },
  {
    name: "Corintios 2",
    chapter: "spa-RVR1960:2Cor",
    posicion: 13,
  },
  {
    name: "Gálatas",
    chapter: "spa-RVR1960:Gal",
    posicion: 48,
  },
  {
    name: "Efesios",
    chapter: "spa-RVR1960:Eph",
    posicion: 57,
  },
  {
    name: "Filipenses",
    chapter: "spa-RVR1960:Phil",
    posicion: 5,
  },
  {
    name: "Colosenses",
    chapter: "spa-RVR1960:Col",
    posicion: 58,
  },
  {
    name: "Tesalonicenses 1",
    chapter: "spa-RVR1960:1Thess",
    posicion: 59,
  },
  {
    name: "Tesalonicenses 2",
    chapter: "spa-RVR1960:2Thess",
    posicion: 19,
  },
  {
    name: "Timoteo 1",
    chapter: "spa-RVR1960:1Tim",
    posicion: 63,
  },
  {
    name: "Timoteo 2",
    chapter: "spa-RVR1960:2Tim",
    posicion: 60,
  },
  {
    name: "Tito",
    chapter: "spa-RVR1960:Titus",
    posicion: 35,
  },
  {
    name: "Filemón",
    chapter: "spa-RVR1960:Phlm",
    posicion: 6,
  },
  {
    name: "Hebreos",
    chapter: "spa-RVR1960:Heb",
    posicion: 36,
  },
  {
    name: "Santiago",
    chapter: "spa-RVR1960:Jas",
    posicion: 46,
  },
  {
    name: "Pedro 1",
    chapter: "spa-RVR1960:1Pet",
    posicion: 47,
  },
  {
    name: "Pedro 2",
    chapter: "spa-RVR1960:2Pet",
    posicion: 26,
  },
  {
    name: "Juan 1",
    chapter: "spa-RVR1960:1John",
    posicion: 49,
  },
  {
    name: "Juan 2",
    chapter: "spa-RVR1960:2John",
    posicion: 14,
  },
  {
    name: "Juan 3",
    chapter: "spa-RVR1960:3John",
    posicion: 56,
  },
  {
    name: "Judas",
    chapter: "spa-RVR1960:Jude",
    posicion: 65,
  },
  {
    name: "Apocalipsis",
    chapter: "spa-RVR1960:Rev",
    posicion: 64,
  },
];

export const libros2 = [
  { name: "génesis", chapter: "spa-RVR1960:Gen" },
  { name: "éxodo", chapter: "spa-RVR1960:Exod" },
  { name: "levítoco", chapter: "spa-RVR1960:Lev" },
  { name: "números", chapter: "spa-RVR1960:Num" },
  { name: "deuteronomio", chapter: "spa-RVR1960:Deut" },
  { name: "josué", chapter: "spa-RVR1960:Josh" },
  { name: "jueces", chapter: "spa-RVR1960:Judg" },
  { name: "rut", chapter: "spa-RVR1960:Ruth" },
  { name: "1a samuel", chapter: "spa-RVR1960:1Sam" },
  { name: "segunda samuel", chapter: "spa-RVR1960:2Sam" },
  { name: "1a reyes", chapter: "spa-RVR1960:1Kgs" },
  { name: "segunda reyes", chapter: "spa-RVR1960:2Kgs" },
  { name: "1a crónicas", chapter: "spa-RVR1960:1Chr" },
  { name: "segunda crónicas", chapter: "spa-RVR1960:2Chr" },
  { name: "esdras", chapter: "spa-RVR1960:Ezra" },
  { name: "nehemías", chapter: "spa-RVR1960:Neh" },
  { name: "ester", chapter: "spa-RVR1960:Esth" },
  { name: "job", chapter: "spa-RVR1960:Job" },
  { name: "salmos", chapter: "spa-RVR1960:Ps" },
  { name: "proverbios", chapter: "spa-RVR1960:Prov" },
  { name: "eclesiastés", chapter: "spa-RVR1960:Eccl" },
  { name: "cantares", chapter: "spa-RVR1960:Song" },
  { name: "isaías", chapter: "spa-RVR1960:Isa" },
  { name: "jeremías", chapter: "spa-RVR1960:Jer" },
  { name: "lamentaciones", chapter: "spa-RVR1960:Lam" },
  { name: "ezequiel", chapter: "spa-RVR1960:Ezek" },
  { name: "daniel", chapter: "spa-RVR1960:Dan" },
  { name: "oseas", chapter: "spa-RVR1960:Hos" },
  { name: "joel", chapter: "spa-RVR1960:Joel" },
  { name: "amós", chapter: "spa-RVR1960:Amos" },
  { name: "abdías", chapter: "spa-RVR1960:Obad" },
  { name: "jonás", chapter: "spa-RVR1960:Jonah" },
  { name: "miqueas", chapter: "spa-RVR1960:Mic" },
  { name: "nahum", chapter: "spa-RVR1960:Nah" },
  { name: "habacuc", chapter: "spa-RVR1960:Hab" },
  { name: "sofonías", chapter: "spa-RVR1960:Zeph" },
  { name: "hageo", chapter: "spa-RVR1960:Hag" },
  { name: "zacarías", chapter: "spa-RVR1960:Zech" },
  { name: "malaquías", chapter: "spa-RVR1960:Mal" },
  { name: "mateo", chapter: "spa-RVR1960:Matt" },
  { name: "marcos", chapter: "spa-RVR1960:Mark" },
  { name: "lucas", chapter: "spa-RVR1960:Luke" },
  { name: "juan", chapter: "spa-RVR1960:John" },
  { name: "hechos", chapter: "spa-RVR1960:Acts" },
  { name: "romanos", chapter: "spa-RVR1960:Rom" },
  { name: "1a corintios", chapter: "spa-RVR1960:1Cor" },
  { name: "segunda corintios", chapter: "spa-RVR1960:2Cor" },
  { name: "gálatas", chapter: "spa-RVR1960:Gal" },
  { name: "efesios", chapter: "spa-RVR1960:Eph" },
  { name: "filipenses", chapter: "spa-RVR1960:Phil" },
  { name: "colosenses", chapter: "spa-RVR1960:Col" },
  { name: "1a tesalonicenses", chapter: "spa-RVR1960:1Thess" },
  { name: "segunda tesalonicenses", chapter: "spa-RVR1960:2Thess" },
  { name: "1a timoteo", chapter: "spa-RVR1960:1Tim" },
  { name: "segunda timoteo", chapter: "spa-RVR1960:2Tim" },
  { name: "tito", chapter: "spa-RVR1960:Titus" },
  { name: "filemón", chapter: "spa-RVR1960:Phlm" },
  { name: "hebreos", chapter: "spa-RVR1960:Heb" },
  { name: "santiago", chapter: "spa-RVR1960:Jas" },
  { name: "1a pedro", chapter: "spa-RVR1960:1Pet" },
  { name: "segunda pedro", chapter: "spa-RVR1960:2Pet" },
  { name: "1a juan", chapter: "spa-RVR1960:1John" },
  { name: "segunda juan", chapter: "spa-RVR1960:2John" },
  { name: "tercera juan", chapter: "spa-RVR1960:3John" },
  { name: "judas", chapter: "spa-RVR1960:Jude" },
  { name: "apocalipsis", chapter: "spa-RVR1960:Rev" },
  { name: "primera juan", chapter: "spa-RVR1960:1John" },
  { name: "primera samuel", chapter: "spa-RVR1960:1Sam" },
  { name: "primera reyes", chapter: "spa-RVR1960:1Kgs" },
  { name: "primera crónicas", chapter: "spa-RVR1960:1Chr" },
  { name: "primera corintios", chapter: "spa-RVR1960:1Cor" },
  { name: "primera tesalonicenses", chapter: "spa-RVR1960:1Thess" },
  { name: "primera timoteo", chapter: "spa-RVR1960:1Tim" },
  { name: "primera pedro", chapter: "spa-RVR1960:1Pet" },
  { name: "primera juan", chapter: "spa-RVR1960:1John" },
];
